// Generated by Crossa. Do not edit.

public class When {

    public fun `when`(value: Int): Int {
        return value
    }

    public fun callKeyword(value: Int): Int {
        return `when`(value)
    }

    public fun render(value: String): String {
        val `when`: String = "\$" + value
        return `when`
    }
}
