#include <algorithm>
#include <chrono>
#include <exception>
#include <filesystem>
#include <fstream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#include "crossa/compiler/ast/Declaration.h"
#include "crossa/compiler/ast/Expression.h"
#include "crossa/compiler/ast/SourceUnit.h"
#include "crossa/compiler/ir/IrDeclaration.h"
#include "crossa/compiler/ir/IrLowerer.h"
#include "crossa/compiler/ir/Program.h"
#include "crossa/compiler/lexer/Lexer.h"
#include "crossa/compiler/lexer/Token.h"
#include "crossa/compiler/lexer/TokenType.h"
#include "crossa/compiler/parser/Parser.h"
#include "crossa/compiler/project/ProjectLinker.h"
#include "crossa/compiler/semantic/SemanticAnalyzer.h"
#include "crossa/compiler/semantic/TypedDeclaration.h"
#include "crossa/compiler/semantic/TypedSourceUnit.h"
#include "crossa/compiler/source/SourceFile.h"
#include "crossa/compiler/types/SemanticType.h"
#include "crossa/utils/Log.h"
#include "crossa/utils/PrintUtils.h"

using namespace std;

namespace crossa::tests {

namespace ast = compiler::ast;
namespace ir = compiler::ir;
namespace lexer = compiler::lexer;
namespace parser = compiler::parser;
namespace semantic = compiler::semantic;
namespace source = compiler::source;
namespace utils = crossa::utils;

// Exercises the complete C++ language frontend and project linker contracts.
// run() fails fast with a precise message when one language invariant breaks.
class LanguageTests final {
public:
    // Executes lexer, parser, semantic, IR, linker, and scripting tests.
    static int run() {
        try {
            verifyLexerTokens();
            verifyParserAst();
            verifyParserImportPosition();
            verifySemanticModel();
            verifyNumericTypes();
            verifySemanticFailure();
            verifyIrLowering();
            verifyProjectLinking();
            verifyProjectLinkingFailures();
            utils::PrintUtils::println("Crossa language tests passed");
            return 0;
        } catch (const exception& error) {
            utils::PrintUtils::println(
                "Crossa language tests failed: " + string(error.what())
            );
            return 1;
        }
    }

private:
    // Stores one isolated temporary project and removes it after each test.
    class TemporaryProject final {
    public:
        // Creates a unique temporary project directory.
        TemporaryProject()
            : root_(filesystem::temp_directory_path() /
                    ("crossa-language-tests-" +
                     to_string(chrono::steady_clock::now()
                                   .time_since_epoch()
                                   .count()))) {
            filesystem::create_directories(root_);
        }

        // Removes the isolated temporary project after the test.
        ~TemporaryProject() {
            error_code error;
            filesystem::remove_all(root_, error);
        }

        // Writes one source fixture below the project root.
        void write(const filesystem::path& relativePath,
                   const string& content) const {
            const filesystem::path filePath = root_ / relativePath;
            filesystem::create_directories(filePath.parent_path());
            ofstream output(filePath);
            if (!output.is_open()) {
                throw runtime_error(
                    "Unable to create test source: " + filePath.string()
                );
            }
            output << content;
        }

        // Returns the temporary project root.
        [[nodiscard]] const filesystem::path& getRoot() const noexcept {
            return root_;
        }

    private:
        filesystem::path root_;
    };

    // Parses source text through the production lexer and parser.
    [[nodiscard]] static ast::SourceUnit parseSource(
        const filesystem::path& sourcePath,
        const string& content
    ) {
        source::SourceFile sourceFile(sourcePath, content);
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        return parser.parse();
    }

    // Returns the diagnostic generated by parsing invalid source text.
    [[nodiscard]] static string captureParseFailure(
        const filesystem::path& sourcePath,
        const string& content
    ) {
        try {
            (void)parseSource(sourcePath, content);
        } catch (const exception& error) {
            return error.what();
        }
        throw runtime_error("Expected parser failure was not raised.");
    }

    // Returns the diagnostic generated by linking an invalid project.
    [[nodiscard]] static string captureLinkFailure(
        const TemporaryProject& project,
        const string& entryName
    ) {
        const filesystem::path entryPath = project.getRoot() / entryName;
        const source::SourceFile sourceFile = source::SourceFile(
            entryPath,
            [&entryPath]() {
                ifstream input(entryPath);
                return string(
                    istreambuf_iterator<char>(input),
                    istreambuf_iterator<char>()
                );
            }()
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        utils::Log log(utils::Log::Level::Error);
        try {
            (void)compiler::project::ProjectLinker::link(
                project.getRoot(),
                entryPath,
                std::move(sourceUnit),
                log
            );
        } catch (const exception& error) {
            return error.what();
        }
        throw runtime_error("Expected linker failure was not raised.");
    }

    // Verifies reserved words, import paths, methods, and punctuation tokens.
    static void verifyLexerTokens() {
        const filesystem::path sourcePath = "lexer.cra";
        const string content =
            "import #models.cra# fun re var model config print assert Int Long "
            "Double String Bool List Json null true false GET POST PUT PATCH DELETE HEAD "
            "OPTIONS TRACE CONNECT @Sync @Async @AsyncAfter ( ) { } [ ] "
            "< > : , = + - * /";
        source::SourceFile sourceFile(sourcePath, content);
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();

        require(tokens.front().getType() == lexer::TokenType::KeywordImport,
                "Lexer did not recognize import keyword.");
        require(tokens.at(1).getType() == lexer::TokenType::ImportPath,
                "Lexer did not recognize hash-delimited import path.");
        require(tokens.at(1).getLexeme(sourceFile) == "#models.cra#",
                "Lexer changed the import path token text.");
        require(countToken(tokens, lexer::TokenType::MethodGet) == 1,
                "Lexer did not recognize GET method token.");
        require(countToken(tokens, lexer::TokenType::MethodConnect) == 1,
                "Lexer did not recognize CONNECT method token.");
        require(countToken(tokens, lexer::TokenType::KeywordAssert) == 1,
                "Lexer did not recognize assert keyword.");
        require(countToken(tokens, lexer::TokenType::KeywordLong) == 1,
                "Lexer did not recognize Long keyword.");
        require(countToken(tokens, lexer::TokenType::KeywordDouble) == 1,
                "Lexer did not recognize Double keyword.");
        require(tokens.back().getType() == lexer::TokenType::EndOfFile,
                "Lexer did not append EndOfFile.");
    }

    // Verifies imports, grouped models, interpolation, and function AST nodes.
    static void verifyParserAst() {
        const ast::SourceUnit sourceUnit = parseSource(
            "parser.cra",
            "import #models.cra#\n"
            "model Post(id: Int, title: String)\n"
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "var label: String = \"post: #title\"\n"
            "print(add(1, 2))\n"
        );
        const vector<unique_ptr<ast::Declaration>>& declarations =
            sourceUnit.getDeclarations();
        require(declarations.size() == 5,
                "Parser produced an unexpected declaration count.");
        require(declarations.at(0)->getKind() == ast::DeclarationKind::Import,
                "Parser did not create an ImportDeclaration.");
        require(
            static_cast<const ast::ImportDeclaration&>(*declarations.at(0))
                    .getFilename() == "models.cra",
            "Parser changed the imported filename."
        );
        require(declarations.at(1)->getKind() == ast::DeclarationKind::Model,
                "Parser did not create a model declaration.");
        require(declarations.at(2)->getKind() == ast::DeclarationKind::Function,
                "Parser did not create a function declaration.");
        const auto& variable = static_cast<const ast::VariableDeclaration&>(
            *declarations.at(3)
        );
        require(variable.getInitializer().getKind() ==
                    ast::ExpressionKind::StringLiteral,
                "Parser did not preserve string interpolation syntax.");
        const auto& stringExpression = static_cast<
            const ast::StringLiteralExpression&>(variable.getInitializer());
        require(stringExpression.getSegments().size() == 2,
                "Parser produced an incorrect interpolation segment count.");
    }

    // Verifies imports after declarations are rejected by the grammar.
    static void verifyParserImportPosition() {
        const string diagnostic = captureParseFailure(
            "import-order.cra",
            "fun ready() { print(\"ready\") }\n"
            "import #models.cra#\n"
        );
        require(
            diagnostic.find("Imports must appear before all declarations") !=
                string::npos,
            "Parser accepted an import after a declaration."
        );
    }

    // Verifies semantic types, symbols, and resolved function signatures.
    static void verifySemanticModel() {
        const filesystem::path sourcePath = "semantic.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "model Post(id: Int)\n"
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "print(add(1, 2))\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();

        require(model.getDeclarations().size() == 3,
                "Semantic analysis changed the declaration count.");
        require(model.getDeclarations().at(0)->getKind() ==
                    semantic::TypedDeclarationKind::Model,
                "Semantic analysis did not type the model.");
        const auto& function = static_cast<
            const semantic::TypedFunctionDeclaration&>(
                *model.getDeclarations().at(1)
            );
        require(function.getReturnType().format() == "Int",
                "Semantic analysis did not resolve function return type.");
    }

    // Verifies Long and Double flow through semantic analysis and IR lowering.
    static void verifyNumericTypes() {
        const filesystem::path sourcePath = "numeric-types.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "model Metric(id: Long, score: Double)\n"
            "fun addLong(a: Long, b: Long): Long { re a + b }\n"
            "fun addDouble(a: Double, b: Double): Double { re a + b }\n"
            "var total: Long = 9000000000\n"
            "var score: Double = 12.5\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();
        const ir::Program program = ir::IrLowerer::lower(model);

        const auto& metric = static_cast<
            const semantic::TypedModelDeclaration&>(
                *model.getDeclarations().at(0)
            );
        require(metric.getFields().at(0).getType().format() == "Long",
                "Semantic analysis did not resolve Long model fields.");
        require(metric.getFields().at(1).getType().format() == "Double",
                "Semantic analysis did not resolve Double model fields.");
        const auto& total = static_cast<const ir::IrVariableDeclaration&>(
            *program.getDeclarations().at(3)
        );
        require(total.getType().format() == "Long",
                "IR lowering did not preserve Long variable type.");
        require(total.getInitializer().getType().format() == "Long",
                "IR lowering did not preserve Long literal type.");
        const auto& score = static_cast<const ir::IrVariableDeclaration&>(
            *program.getDeclarations().at(4)
        );
        require(score.getType().format() == "Double",
                "IR lowering did not preserve Double variable type.");
        require(score.getInitializer().getKind() ==
                    ir::IrExpressionKind::DoubleConstant,
                "IR lowering did not produce a Double constant.");
    }

    // Verifies semantic diagnostics for unresolved types.
    static void verifySemanticFailure() {
        const filesystem::path sourcePath = "semantic-failure.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "fun broken(): Missing { re 1 }\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);

        try {
            (void)analyzer.analyze();
        } catch (const exception& error) {
            require(
                string(error.what()).find("Unknown Crossa type") !=
                    string::npos,
                "Semantic failure did not identify the unknown type."
            );
            return;
        }
        throw runtime_error("Semantic analysis accepted an unknown type.");
    }

    // Verifies typed semantic declarations lower into platform-neutral IR.
    static void verifyIrLowering() {
        const filesystem::path sourcePath = "ir.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "print(add(1, 2))\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();
        const ir::Program program = ir::IrLowerer::lower(model);

        require(program.getDeclarations().size() == 2,
                "IR lowering changed the declaration count.");
        require(program.getDeclarations().at(0)->getKind() ==
                    ir::IrDeclarationKind::Function,
                "IR lowering did not preserve function declarations.");
        require(program.getDeclarations().at(1)->getKind() ==
                    ir::IrDeclarationKind::Expression,
                "IR lowering did not preserve top-level scripting calls.");
    }

    // Verifies nested, transitive, grouped-model, and diamond imports.
    static void verifyProjectLinking() {
        TemporaryProject project;
        project.write(
            "domain/models.cra",
            "model Post(id: Int)\nmodel Author(id: Int)\n"
        );
        project.write(
            "network/postRequests.cra",
            "import #models.cra#\n"
            "fun fetchPosts(): List<Post> {\n"
            "    re CrossaRequest {\n"
            "        url: \"https://example.test/posts\", method: GET\n"
            "    }\n"
            "}\n"
        );
        project.write(
            "repositories/postsRepository.cra",
            "import #postRequests.cra#\n"
            "fun getPosts(): List<Post> { re fetchPosts() }\n"
        );
        project.write(
            "entry.cra",
            "import #postsRepository.cra#\n"
            "print(1)\n"
        );

        const filesystem::path entryPath = project.getRoot() / "entry.cra";
        const source::SourceFile sourceFile(
            entryPath,
            "import #postsRepository.cra#\nprint(1)\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        utils::Log log(utils::Log::Level::Error);
        ast::SourceUnit linked = compiler::project::ProjectLinker::link(
            project.getRoot(),
            entryPath,
            std::move(sourceUnit),
            log
        );

        require(linked.getDeclarations().size() == 5,
                "Project linker did not merge all reachable declarations.");
        require(linked.getDeclarations().at(0)->getKind() ==
                    ast::DeclarationKind::Model,
                "Project linker did not place dependencies first.");
        for (const unique_ptr<ast::Declaration>& declaration :
             linked.getDeclarations()) {
            require(declaration->getKind() != ast::DeclarationKind::Import,
                    "Project linker left an ImportDeclaration in the AST.");
        }
    }

    // Verifies missing, ambiguous, circular, and side-effect imports fail.
    static void verifyProjectLinkingFailures() {
        TemporaryProject missingProject;
        missingProject.write(
            "missingEntry.cra",
            "import #doesNotExist.cra#\n"
        );
        require(
            captureLinkFailure(missingProject, "missingEntry.cra").find(
                "was not found"
            ) != string::npos,
            "Missing import did not produce a linker diagnostic."
        );

        TemporaryProject ambiguousProject;
        ambiguousProject.write(
            "entry.cra",
            "import #duplicate.cra#\n"
        );
        ambiguousProject.write("one/duplicate.cra", "fun one() {}\n");
        ambiguousProject.write("two/duplicate.cra", "fun two() {}\n");
        require(
            captureLinkFailure(ambiguousProject, "entry.cra").find(
                "is ambiguous"
            ) != string::npos,
            "Ambiguous import did not produce a linker diagnostic."
        );

        TemporaryProject cycleProject;
        cycleProject.write("one.cra", "import #two.cra#\n");
        cycleProject.write("two.cra", "import #one.cra#\n");
        require(
            captureLinkFailure(cycleProject, "one.cra").find(
                "Circular import detected"
            ) != string::npos,
            "Circular import did not produce a linker diagnostic."
        );

        TemporaryProject sideEffectProject;
        sideEffectProject.write("entry.cra", "import #sideEffect.cra#\n");
        sideEffectProject.write("sideEffect.cra", "print(\"hidden\")\n");
        require(
            captureLinkFailure(sideEffectProject, "entry.cra").find(
                "top-level execution belongs to the entry file"
            ) != string::npos,
            "Imported top-level execution was not rejected."
        );
    }

    // Counts occurrences of one token category in a token stream.
    [[nodiscard]] static size_t countToken(
        const vector<lexer::Token>& tokens,
        lexer::TokenType type
    ) noexcept {
        return count_if(
            tokens.begin(),
            tokens.end(),
            [type](const lexer::Token& token) {
                return token.getType() == type;
            }
        );
    }

    // Fails a test with a stable human-readable assertion message.
    static void require(bool condition, const string& message) {
        if (!condition) {
            throw runtime_error(message);
        }
    }
};

}

// Starts the standalone Crossa language unit-test executable.
int main() {
    return crossa::tests::LanguageTests::run();
}
