#include <algorithm>
#include <chrono>
#include <exception>
#include <filesystem>
#include <fstream>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#include "crossa/compiler/ast/Declaration.h"
#include "crossa/compiler/ast/Expression.h"
#include "crossa/compiler/ast/SourceUnit.h"
#include "crossa/compiler/generators/kotlin/KotlinGenerator.h"
#include "crossa/compiler/ir/IrDeclaration.h"
#include "crossa/compiler/ir/IrLowerer.h"
#include "crossa/compiler/ir/Program.h"
#include "crossa/compiler/lexer/Lexer.h"
#include "crossa/compiler/lexer/Token.h"
#include "crossa/compiler/lexer/TokenType.h"
#include "crossa/compiler/parser/Parser.h"
#include "crossa/compiler/project/ProjectLinker.h"
#include "crossa/compiler/semantic/SemanticAnalyzer.h"
#include "crossa/compiler/semantic/TypedDeclaration.h"
#include "crossa/compiler/semantic/TypedSourceUnit.h"
#include "crossa/compiler/source/SourceFile.h"
#include "crossa/compiler/types/SemanticType.h"
#include "crossa/utils/Log.h"
#include "crossa/utils/PrintUtils.h"

using namespace std;

namespace crossa::tests {

namespace ast = compiler::ast;
namespace ir = compiler::ir;
namespace lexer = compiler::lexer;
namespace parser = compiler::parser;
namespace semantic = compiler::semantic;
namespace source = compiler::source;
namespace utils = crossa::utils;

// Exercises the complete C++ language frontend and project linker contracts.
// run() fails fast with a precise message when one language invariant breaks.
class LanguageTests final {
public:
    // Executes lexer, parser, semantic, IR, linker, and scripting tests.
    static int run() {
        try {
            verifyLexerTokens();
            verifyParserAst();
            verifyConditionals();
            verifyParserImportPosition();
            verifySemanticModel();
            verifyNumericTypes();
            verifySemanticFailure();
            verifyIrLowering();
            verifyKotlinGeneration();
            verifyProjectLinking();
            verifyProjectLinkingFailures();
            utils::PrintUtils::println("Crossa language tests passed");
            return 0;
        } catch (const exception& error) {
            utils::PrintUtils::println(
                "Crossa language tests failed: " + string(error.what())
            );
            return 1;
        }
    }

private:
    // Stores one isolated temporary project and removes it after each test.
    class TemporaryProject final {
    public:
        // Creates a unique temporary project directory.
        TemporaryProject()
            : root_(filesystem::temp_directory_path() /
                    ("crossa-language-tests-" +
                     to_string(chrono::steady_clock::now()
                                   .time_since_epoch()
                                   .count()))) {
            filesystem::create_directories(root_);
        }

        // Removes the isolated temporary project after the test.
        ~TemporaryProject() {
            error_code error;
            filesystem::remove_all(root_, error);
        }

        // Writes one source fixture below the project root.
        void write(const filesystem::path& relativePath,
                   const string& content) const {
            const filesystem::path filePath = root_ / relativePath;
            filesystem::create_directories(filePath.parent_path());
            ofstream output(filePath);
            if (!output.is_open()) {
                throw runtime_error(
                    "Unable to create test source: " + filePath.string()
                );
            }
            output << content;
        }

        // Returns the temporary project root.
        [[nodiscard]] const filesystem::path& getRoot() const noexcept {
            return root_;
        }

    private:
        filesystem::path root_;
    };

    // Parses source text through the production lexer and parser.
    [[nodiscard]] static ast::SourceUnit parseSource(
        const filesystem::path& sourcePath,
        const string& content
    ) {
        source::SourceFile sourceFile(sourcePath, content);
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        return parser.parse();
    }

    // Returns the diagnostic generated by parsing invalid source text.
    [[nodiscard]] static string captureParseFailure(
        const filesystem::path& sourcePath,
        const string& content
    ) {
        try {
            (void)parseSource(sourcePath, content);
        } catch (const exception& error) {
            return error.what();
        }
        throw runtime_error("Expected parser failure was not raised.");
    }

    // Returns the diagnostic generated by linking an invalid project.
    [[nodiscard]] static string captureLinkFailure(
        const TemporaryProject& project,
        const string& entryName
    ) {
        const filesystem::path entryPath = project.getRoot() / entryName;
        const source::SourceFile sourceFile = source::SourceFile(
            entryPath,
            [&entryPath]() {
                ifstream input(entryPath);
                return string(
                    istreambuf_iterator<char>(input),
                    istreambuf_iterator<char>()
                );
            }()
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        utils::Log log(utils::Log::Level::Error);
        try {
            (void)compiler::project::ProjectLinker::link(
                project.getRoot(),
                entryPath,
                std::move(sourceUnit),
                log
            );
        } catch (const exception& error) {
            return error.what();
        }
        throw runtime_error("Expected linker failure was not raised.");
    }

    // Verifies reserved words, import paths, methods, and punctuation tokens.
    static void verifyLexerTokens() {
        const filesystem::path sourcePath = "lexer.cra";
        const string content =
            "import #models.cra# fun re if else var model config print assert Int Long "
            "Double String Bool List Json null true false GET POST PUT PATCH DELETE HEAD "
            "OPTIONS TRACE CONNECT @Sync @Async @AsyncAfter ( ) { } [ ] "
            "< > <= >= : , = == != && || ! + - * /";
        source::SourceFile sourceFile(sourcePath, content);
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();

        require(tokens.front().getType() == lexer::TokenType::KeywordImport,
                "Lexer did not recognize import keyword.");
        require(tokens.at(1).getType() == lexer::TokenType::ImportPath,
                "Lexer did not recognize hash-delimited import path.");
        require(tokens.at(1).getLexeme(sourceFile) == "#models.cra#",
                "Lexer changed the import path token text.");
        require(countToken(tokens, lexer::TokenType::MethodGet) == 1,
                "Lexer did not recognize GET method token.");
        require(countToken(tokens, lexer::TokenType::MethodConnect) == 1,
                "Lexer did not recognize CONNECT method token.");
        require(countToken(tokens, lexer::TokenType::KeywordAssert) == 1,
                "Lexer did not recognize assert keyword.");
        require(countToken(tokens, lexer::TokenType::KeywordIf) == 1,
                "Lexer did not recognize if keyword.");
        require(countToken(tokens, lexer::TokenType::KeywordElse) == 1,
                "Lexer did not recognize else keyword.");
        require(countToken(tokens, lexer::TokenType::EqualEqual) == 1,
                "Lexer did not recognize equality operator.");
        require(countToken(tokens, lexer::TokenType::BangEqual) == 1,
                "Lexer did not recognize inequality operator.");
        require(countToken(tokens, lexer::TokenType::LessEqual) == 1,
                "Lexer did not recognize less-than-or-equal operator.");
        require(countToken(tokens, lexer::TokenType::GreaterEqual) == 1,
                "Lexer did not recognize greater-than-or-equal operator.");
        require(countToken(tokens, lexer::TokenType::AndAnd) == 1,
                "Lexer did not recognize logical-and operator.");
        require(countToken(tokens, lexer::TokenType::OrOr) == 1,
                "Lexer did not recognize logical-or operator.");
        require(countToken(tokens, lexer::TokenType::Bang) == 1,
                "Lexer did not recognize logical-not operator.");
        require(countToken(tokens, lexer::TokenType::KeywordLong) == 1,
                "Lexer did not recognize Long keyword.");
        require(countToken(tokens, lexer::TokenType::KeywordDouble) == 1,
                "Lexer did not recognize Double keyword.");
        require(tokens.back().getType() == lexer::TokenType::EndOfFile,
                "Lexer did not append EndOfFile.");
    }

    static void verifyConditionals() {
        const filesystem::path sourcePath = "conditionals.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "fun classify(value: Int): String {\n"
            "    if (value > 10) { re \"high\" }\n"
            "    else if (value == 10) { re \"equal\" }\n"
            "    else { re \"low\" }\n"
            "}\n"
            "fun choose(flag: Bool): Int {\n"
            "    if (flag) { var selected: Int = 1 re selected }\n"
            "    else { re 2 }\n"
            "}\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        const auto& classify = static_cast<const ast::FunctionDeclaration&>(
            *sourceUnit.getDeclarations().at(0)
        );
        require(classify.getStatements().at(0)->getKind() == ast::StatementKind::If,
                "Parser did not create an if statement.");
        const auto& conditional = static_cast<const ast::IfStatement&>(
            *classify.getStatements().at(0)
        );
        require(conditional.getElseStatements() != nullptr,
                "Parser did not preserve the else branch.");
        require(conditional.getElseStatements()->at(0)->getKind() ==
                    ast::StatementKind::If,
                "Parser did not preserve the else-if chain.");

        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();
        const auto& typedClassify = static_cast<
            const semantic::TypedFunctionDeclaration&>(
                *model.getDeclarations().at(0)
            );
        const auto& typedConditional = static_cast<
            const semantic::TypedIfStatement&>(
                *typedClassify.getStatements().at(0)
            );
        require(typedConditional.getCondition().getType().getKind() ==
                    compiler::types::SemanticTypeKind::Bool,
                "Semantic analysis did not type the if condition as Bool.");

        const ir::Program program = ir::IrLowerer::lower(model);
        const auto& irClassify = static_cast<const ir::IrFunctionDeclaration&>(
            *program.getDeclarations().at(0)
        );
        require(irClassify.getStatements().at(0)->getKind() == ir::IrStatementKind::If,
                "IR lowering did not create an if instruction.");

        const source::SourceFile invalidConditionFile(
            "invalid-condition.cra",
            "fun broken(): Int { if (1) { re 1 } else { re 2 } }\n"
        );
        lexer::Lexer invalidLexer(invalidConditionFile);
        const vector<lexer::Token> invalidTokens = invalidLexer.tokenize();
        parser::Parser invalidParser(invalidTokens, invalidConditionFile);
        ast::SourceUnit invalidSource = invalidParser.parse();
        semantic::SemanticAnalyzer invalidAnalyzer(
            invalidSource,
            invalidConditionFile
        );
        try {
            (void)invalidAnalyzer.analyze();
        } catch (const exception& error) {
            require(string(error.what()).find("must be Bool") != string::npos,
                    "Semantic analysis did not reject a non-Bool condition.");
            return;
        }
        throw runtime_error("Semantic analysis accepted a non-Bool condition.");
    }

    // Verifies imports, grouped models, interpolation, and function AST nodes.
    static void verifyParserAst() {
        const ast::SourceUnit sourceUnit = parseSource(
            "parser.cra",
            "import #models.cra#\n"
            "model Post(id: Int, title: String)\n"
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "var label: String = \"post: #title\"\n"
            "print(add(1, 2))\n"
        );
        const vector<unique_ptr<ast::Declaration>>& declarations =
            sourceUnit.getDeclarations();
        require(declarations.size() == 5,
                "Parser produced an unexpected declaration count.");
        require(declarations.at(0)->getKind() == ast::DeclarationKind::Import,
                "Parser did not create an ImportDeclaration.");
        require(
            static_cast<const ast::ImportDeclaration&>(*declarations.at(0))
                    .getFilename() == "models.cra",
            "Parser changed the imported filename."
        );
        require(declarations.at(1)->getKind() == ast::DeclarationKind::Model,
                "Parser did not create a model declaration.");
        require(declarations.at(2)->getKind() == ast::DeclarationKind::Function,
                "Parser did not create a function declaration.");
        const auto& variable = static_cast<const ast::VariableDeclaration&>(
            *declarations.at(3)
        );
        require(variable.getInitializer().getKind() ==
                    ast::ExpressionKind::StringLiteral,
                "Parser did not preserve string interpolation syntax.");
        const auto& stringExpression = static_cast<
            const ast::StringLiteralExpression&>(variable.getInitializer());
        require(stringExpression.getSegments().size() == 2,
                "Parser produced an incorrect interpolation segment count.");
    }

    // Verifies imports after declarations are rejected by the grammar.
    static void verifyParserImportPosition() {
        const string diagnostic = captureParseFailure(
            "import-order.cra",
            "fun ready() { print(\"ready\") }\n"
            "import #models.cra#\n"
        );
        require(
            diagnostic.find("Imports must appear before all declarations") !=
                string::npos,
            "Parser accepted an import after a declaration."
        );
    }

    // Verifies semantic types, symbols, and resolved function signatures.
    static void verifySemanticModel() {
        const filesystem::path sourcePath = "semantic.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "model Post(id: Int)\n"
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "print(add(1, 2))\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();

        require(model.getDeclarations().size() == 3,
                "Semantic analysis changed the declaration count.");
        require(model.getDeclarations().at(0)->getKind() ==
                    semantic::TypedDeclarationKind::Model,
                "Semantic analysis did not type the model.");
        const auto& function = static_cast<
            const semantic::TypedFunctionDeclaration&>(
                *model.getDeclarations().at(1)
            );
        require(function.getReturnType().format() == "Int",
                "Semantic analysis did not resolve function return type.");
    }

    // Verifies Long and Double flow through semantic analysis and IR lowering.
    static void verifyNumericTypes() {
        const filesystem::path sourcePath = "numeric-types.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "model Metric(id: Long, score: Double)\n"
            "fun addLong(a: Long, b: Long): Long { re a + b }\n"
            "fun addDouble(a: Double, b: Double): Double { re a + b }\n"
            "var total: Long = 9000000000\n"
            "var score: Double = 12.5\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();
        const ir::Program program = ir::IrLowerer::lower(model);

        const auto& metric = static_cast<
            const semantic::TypedModelDeclaration&>(
                *model.getDeclarations().at(0)
            );
        require(metric.getFields().at(0).getType().format() == "Long",
                "Semantic analysis did not resolve Long model fields.");
        require(metric.getFields().at(1).getType().format() == "Double",
                "Semantic analysis did not resolve Double model fields.");
        const auto& total = static_cast<const ir::IrVariableDeclaration&>(
            *program.getDeclarations().at(3)
        );
        require(total.getType().format() == "Long",
                "IR lowering did not preserve Long variable type.");
        require(total.getInitializer().getType().format() == "Long",
                "IR lowering did not preserve Long literal type.");
        const auto& score = static_cast<const ir::IrVariableDeclaration&>(
            *program.getDeclarations().at(4)
        );
        require(score.getType().format() == "Double",
                "IR lowering did not preserve Double variable type.");
        require(score.getInitializer().getKind() ==
                    ir::IrExpressionKind::DoubleConstant,
                "IR lowering did not produce a Double constant.");
    }

    // Verifies semantic diagnostics for unresolved types.
    static void verifySemanticFailure() {
        const filesystem::path sourcePath = "semantic-failure.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "fun broken(): Missing { re 1 }\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);

        try {
            (void)analyzer.analyze();
        } catch (const exception& error) {
            require(
                string(error.what()).find("Unknown Crossa type") !=
                    string::npos,
                "Semantic failure did not identify the unknown type."
            );
            return;
        }
        throw runtime_error("Semantic analysis accepted an unknown type.");
    }

    // Verifies typed semantic declarations lower into platform-neutral IR.
    static void verifyIrLowering() {
        const filesystem::path sourcePath = "ir.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "print(add(1, 2))\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();
        const ir::Program program = ir::IrLowerer::lower(model);

        require(program.getDeclarations().size() == 2,
                "IR lowering changed the declaration count.");
        require(program.getDeclarations().at(0)->getKind() ==
                    ir::IrDeclarationKind::Function,
                "IR lowering did not preserve function declarations.");
        require(program.getDeclarations().at(1)->getKind() ==
                    ir::IrDeclarationKind::Expression,
                "IR lowering did not preserve top-level scripting calls.");
    }

    // Verifies deterministic pure Kotlin generation from typed Crossa IR.
    static void verifyKotlinGeneration() {
        const filesystem::path sourcePath = "Math.cra";
        const source::SourceFile sourceFile(
            sourcePath,
            "fun add(a: Int, b: Int): Int { re a + b }\n"
            "fun selectValue(first: Int, second: Int, enabled: Bool): Int {\n"
            "    if (!enabled) { re second }\n"
            "    else if (first >= second && enabled) { re add(first, second) }\n"
            "    else { re (first + second) * 2 }\n"
            "}\n"
            "fun describe(label: String, longValue: Long, ratio: Double, enabled: Bool): String {\n"
            "    var when: String = \"label: #label\"\n"
            "    if (enabled || !enabled) { re when } else { re label }\n"
            "}\n"
            "fun when(value: Int): Int { re value }\n"
            "fun callKeyword(value: Int): Int { re when(value) }\n"
            "fun log(value: String) { print(value) }\n"
            "fun compare(a: Int, b: Int): Int {\n"
            "    if (a == b || a != b && a < b || a <= b || a > b || a >= b) { re a }\n"
            "    else { re b }\n"
            "}\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        semantic::SemanticAnalyzer analyzer(sourceUnit, sourceFile);
        const semantic::TypedSourceUnit model = analyzer.analyze();
        const ir::Program program = ir::IrLowerer::lower(model);
        const compiler::generators::kotlin::KotlinGenerator generator;
        const auto firstGenerated = generator.generate(program);
        const auto secondGenerated = generator.generate(program);

        const string expected =
            "// Generated by Crossa. Do not edit.\n"
            "\n"
            "public class Math {\n"
            "\n"
            "    public fun add(a: Int, b: Int): Int {\n"
            "        return a + b\n"
            "    }\n"
            "\n"
            "    public fun selectValue(\n"
            "        first: Int,\n"
            "        second: Int,\n"
            "        enabled: Boolean\n"
            "    ): Int {\n"
            "        if (!enabled) {\n"
            "            return second\n"
            "        } else if (first >= second && enabled) {\n"
            "            return add(first, second)\n"
            "        } else {\n"
            "            return (first + second) * 2\n"
            "        }\n"
            "    }\n"
            "\n"
            "    public fun describe(\n"
            "        label: String,\n"
            "        longValue: Long,\n"
            "        ratio: Double,\n"
            "        enabled: Boolean\n"
            "    ): String {\n"
            "        val `when`: String = \"label: \" + label\n"
            "        if (enabled || !enabled) {\n"
            "            return `when`\n"
            "        } else {\n"
            "            return label\n"
            "        }\n"
            "    }\n"
            "\n"
            "    public fun `when`(value: Int): Int {\n"
            "        return value\n"
            "    }\n"
            "\n"
            "    public fun callKeyword(value: Int): Int {\n"
            "        return `when`(value)\n"
            "    }\n"
            "\n"
            "    public fun log(value: String) {\n"
            "        println(value)\n"
            "    }\n"
            "\n"
            "    public fun compare(a: Int, b: Int): Int {\n"
            "        if ((((a == b || a != b && a < b) || a <= b) || a > b) || a >= b) {\n"
            "            return a\n"
            "        } else {\n"
            "            return b\n"
            "        }\n"
            "    }\n"
            "}\n";
        require(firstGenerated.getFileName() == "Math.kt",
                "Kotlin generation did not preserve the source-unit file name.");
        require(firstGenerated.getContent() == expected,
                "Kotlin generation did not produce canonical source.");
        require(firstGenerated.getContent() == secondGenerated.getContent(),
                "Kotlin generation was not byte-for-byte deterministic.");

        const auto packagedGenerated = generator.generate(
            program,
            string("com.example.crossa")
        );
        require(
            packagedGenerated.getContent().find(
                "// Generated by Crossa. Do not edit.\n\n"
                "package com.example.crossa\n\n"
            ) == 0,
            "Kotlin generation did not write the configured package directive."
        );
        bool rejectedInvalidPackage = false;
        try {
            (void)generator.generate(program, string("com..example"));
        } catch (const exception& error) {
            rejectedInvalidPackage = true;
            require(
                string(error.what()).find("config packageName") != string::npos,
                "Kotlin generation did not diagnose an invalid package name."
            );
        }
        require(
            rejectedInvalidPackage,
            "Kotlin generation accepted an invalid package name."
        );

        const source::SourceFile keywordSourceFile(
            "when.cra",
            "fun value(): String { re \"$value\" }\n"
        );
        lexer::Lexer keywordLexer(keywordSourceFile);
        const vector<lexer::Token> keywordTokens = keywordLexer.tokenize();
        parser::Parser keywordParser(keywordTokens, keywordSourceFile);
        ast::SourceUnit keywordSource = keywordParser.parse();
        semantic::SemanticAnalyzer keywordAnalyzer(
            keywordSource,
            keywordSourceFile
        );
        const semantic::TypedSourceUnit keywordModel = keywordAnalyzer.analyze();
        const ir::Program keywordProgram = ir::IrLowerer::lower(keywordModel);
        const auto keywordGenerated = generator.generate(keywordProgram);
        require(keywordGenerated.getFileName() == "When.kt",
                "Kotlin generation did not use PascalCase for a source-unit file name.");
        require(keywordGenerated.getContent().find("public class When") !=
                    string::npos,
                "Kotlin generation did not use PascalCase for a source-unit class.");
        require(keywordGenerated.getContent().find("\"\\$value\"") !=
                    string::npos,
                "Kotlin generation did not escape Kotlin string templates.");

        const source::SourceFile snakeCaseSourceFile(
            "posts_api.cra",
            "fun fetch(): Int { re 1 }\n"
        );
        lexer::Lexer snakeCaseLexer(snakeCaseSourceFile);
        const vector<lexer::Token> snakeCaseTokens = snakeCaseLexer.tokenize();
        parser::Parser snakeCaseParser(snakeCaseTokens, snakeCaseSourceFile);
        ast::SourceUnit snakeCaseSource = snakeCaseParser.parse();
        semantic::SemanticAnalyzer snakeCaseAnalyzer(
            snakeCaseSource,
            snakeCaseSourceFile
        );
        const semantic::TypedSourceUnit snakeCaseModel =
            snakeCaseAnalyzer.analyze();
        const ir::Program snakeCaseProgram = ir::IrLowerer::lower(snakeCaseModel);
        const auto snakeCaseGenerated = generator.generate(snakeCaseProgram);
        require(snakeCaseGenerated.getFileName() == "PostsApi.kt",
                "Kotlin generation did not format snake_case source file names.");
        require(snakeCaseGenerated.getContent().find("public class PostsApi") !=
                    string::npos,
                "Kotlin generation did not format snake_case source classes.");

        const source::SourceFile requestFile(
            "Request.cra",
            "fun fetch(): Json {\n"
            "    re CrossaRequest { url: \"https://example.test/users\", method: GET }\n"
            "}\n"
        );
        lexer::Lexer requestLexer(requestFile);
        const vector<lexer::Token> requestTokens = requestLexer.tokenize();
        parser::Parser requestParser(requestTokens, requestFile);
        ast::SourceUnit requestSource = requestParser.parse();
        semantic::SemanticAnalyzer requestAnalyzer(requestSource, requestFile);
        const semantic::TypedSourceUnit requestModel = requestAnalyzer.analyze();
        const ir::Program requestProgram = ir::IrLowerer::lower(requestModel);
        try {
            (void)generator.generate(requestProgram);
        } catch (const exception& error) {
            require(
                string(error.what()).find("runtime-backed expression 'CrossaRequest'") !=
                    string::npos,
                "Kotlin generation did not reject CrossaRequest explicitly."
            );
            return;
        }
        throw runtime_error("Kotlin generation accepted CrossaRequest.");
    }

    // Verifies nested, transitive, grouped-model, and diamond imports.
    static void verifyProjectLinking() {
        TemporaryProject project;
        project.write(
            "domain/models.cra",
            "model Post(id: Int)\nmodel Author(id: Int)\n"
        );
        project.write(
            "network/postRequests.cra",
            "import #models.cra#\n"
            "fun fetchPosts(): List<Post> {\n"
            "    re CrossaRequest {\n"
            "        url: \"https://example.test/posts\", method: GET\n"
            "    }\n"
            "}\n"
        );
        project.write(
            "repositories/postsRepository.cra",
            "import #postRequests.cra#\n"
            "fun getPosts(): List<Post> { re fetchPosts() }\n"
        );
        project.write(
            "entry.cra",
            "import #postsRepository.cra#\n"
            "print(1)\n"
        );

        const filesystem::path entryPath = project.getRoot() / "entry.cra";
        const source::SourceFile sourceFile(
            entryPath,
            "import #postsRepository.cra#\nprint(1)\n"
        );
        lexer::Lexer lexer(sourceFile);
        const vector<lexer::Token> tokens = lexer.tokenize();
        parser::Parser parser(tokens, sourceFile);
        ast::SourceUnit sourceUnit = parser.parse();
        utils::Log log(utils::Log::Level::Error);
        ast::SourceUnit linked = compiler::project::ProjectLinker::link(
            project.getRoot(),
            entryPath,
            std::move(sourceUnit),
            log
        );

        require(linked.getDeclarations().size() == 5,
                "Project linker did not merge all reachable declarations.");
        require(linked.getDeclarations().at(0)->getKind() ==
                    ast::DeclarationKind::Model,
                "Project linker did not place dependencies first.");
        for (const unique_ptr<ast::Declaration>& declaration :
             linked.getDeclarations()) {
            require(declaration->getKind() != ast::DeclarationKind::Import,
                    "Project linker left an ImportDeclaration in the AST.");
        }
    }

    // Verifies missing, ambiguous, circular, and side-effect imports fail.
    static void verifyProjectLinkingFailures() {
        TemporaryProject missingProject;
        missingProject.write(
            "missingEntry.cra",
            "import #doesNotExist.cra#\n"
        );
        require(
            captureLinkFailure(missingProject, "missingEntry.cra").find(
                "was not found"
            ) != string::npos,
            "Missing import did not produce a linker diagnostic."
        );

        TemporaryProject ambiguousProject;
        ambiguousProject.write(
            "entry.cra",
            "import #duplicate.cra#\n"
        );
        ambiguousProject.write("one/duplicate.cra", "fun one() {}\n");
        ambiguousProject.write("two/duplicate.cra", "fun two() {}\n");
        require(
            captureLinkFailure(ambiguousProject, "entry.cra").find(
                "is ambiguous"
            ) != string::npos,
            "Ambiguous import did not produce a linker diagnostic."
        );

        TemporaryProject cycleProject;
        cycleProject.write("one.cra", "import #two.cra#\n");
        cycleProject.write("two.cra", "import #one.cra#\n");
        require(
            captureLinkFailure(cycleProject, "one.cra").find(
                "Circular import detected"
            ) != string::npos,
            "Circular import did not produce a linker diagnostic."
        );

        TemporaryProject sideEffectProject;
        sideEffectProject.write("entry.cra", "import #sideEffect.cra#\n");
        sideEffectProject.write("sideEffect.cra", "print(\"hidden\")\n");
        require(
            captureLinkFailure(sideEffectProject, "entry.cra").find(
                "top-level execution belongs to the entry file"
            ) != string::npos,
            "Imported top-level execution was not rejected."
        );
    }

    // Counts occurrences of one token category in a token stream.
    [[nodiscard]] static size_t countToken(
        const vector<lexer::Token>& tokens,
        lexer::TokenType type
    ) noexcept {
        return count_if(
            tokens.begin(),
            tokens.end(),
            [type](const lexer::Token& token) {
                return token.getType() == type;
            }
        );
    }

    // Fails a test with a stable human-readable assertion message.
    static void require(bool condition, const string& message) {
        if (!condition) {
            throw runtime_error(message);
        }
    }
};

}

// Starts the standalone Crossa language unit-test executable.
int main() {
    return crossa::tests::LanguageTests::run();
}
