// Generated by Crossa. Do not edit.

public class Flow {

    public fun notify(message: String) {
        println(message)
    }

    public fun choose(
        first: Int,
        second: Int,
        third: Int
    ): Int {
        if (first > second) {
            return first
        } else if (second > third) {
            return second
        } else {
            return third
        }
    }
}
