// Generated by Crossa. Do not edit.

package com.example.crossa

public class Math {

    public fun add(a: Int, b: Int): Int {
        return a + b
    }

    public fun selectValue(
        first: Int,
        second: Int,
        enabled: Boolean
    ): Int {
        if (!enabled) {
            return second
        } else if (first >= second && enabled) {
            return add(first, second)
        } else {
            return (first + second) * 2
        }
    }
}
