#include "crossa/compiler/generators/kotlin/KotlinGenerator.h"

#include <sstream>
#include <stdexcept>

#include "crossa/compiler/ir/IrCrossaRequestExpression.h"
#include "crossa/compiler/generators/kotlin/KotlinExpressionEmitter.h"
#include "crossa/compiler/generators/kotlin/KotlinSourceWriter.h"
#include "crossa/compiler/generators/kotlin/KotlinStatementEmitter.h"
#include "crossa/compiler/ir/IrJsonExpression.h"

using namespace std;

namespace crossa::compiler::generators::kotlin {

    // Generates the Kotlin file identity and canonical source for one IR program.
    KotlinGeneratedSource KotlinGenerator::generate(
        const ir::Program& program,
        const optional<string>& packageName
    ) const {
        if (program.getIdentity().empty()) {
            failInvariant("Program source-unit identity is empty.");
        }

        KotlinSourceWriter writer;
        writer.writeLine("// Generated by Crossa. Do not edit.");
        writer.writeLine();
        emitPackageDirective(packageName, writer);
        writer.beginBlock(
            "public class " + identifierEscaper_.escape(program.getIdentity())
        );

        ModelMap models;
        for (const unique_ptr<ir::IrDeclaration>& declaration :
             program.getDeclarations()) {
            if (declaration->getKind() == ir::IrDeclarationKind::Model) {
                const auto& model = static_cast<const ir::IrModelDeclaration&>(
                    *declaration
                );
                models.emplace(model.getName(), &model);
            }
        }

        for (const unique_ptr<ir::IrDeclaration>& declaration :
             program.getDeclarations()) {
            if (declaration->getKind() == ir::IrDeclarationKind::Model) {
                writer.writeLine();
                emitModel(
                    static_cast<const ir::IrModelDeclaration&>(*declaration),
                    writer
                );
                continue;
            }
            if (declaration->getKind() == ir::IrDeclarationKind::Function) {
                writer.writeLine();
                emitFunction(
                    static_cast<const ir::IrFunctionDeclaration&>(*declaration),
                    models,
                    writer
                );
                continue;
            }
            if (declaration->getKind() == ir::IrDeclarationKind::Expression) {
                continue;
            }
            failUnsupported("top-level declaration");
        }

        for (const auto& entry : models) {
            writer.writeLine();
            emitModelMapper(*entry.second, writer);
        }

        writer.endBlock();
        return KotlinGeneratedSource(getFileName(program), writer.getSource());
    }

    void KotlinGenerator::emitModel(
        const ir::IrModelDeclaration& model,
        KotlinSourceWriter& writer
    ) const {
        writer.writeLine("public data class " + identifierEscaper_.escape(model.getName()) + "(");
        writer.indent();
        const vector<ir::IrModelField>& fields = model.getFields();
        for (size_t index = 0; index < fields.size(); ++index) {
            writer.writeLine(
                "public val " + identifierEscaper_.escape(fields[index].getName()) +
                ": " + typeMapper_.mapValueType(fields[index].getType()) +
                (index + 1 < fields.size() ? "," : "")
            );
        }
        writer.dedent();
        writer.writeLine(")");
    }

    // Emits one pure synchronous Kotlin function.
    void KotlinGenerator::emitFunction(
        const ir::IrFunctionDeclaration& function,
        const ModelMap& models,
        KotlinSourceWriter& writer
    ) const {
        if (function.getExecutionPolicy() == ir::IrExecutionPolicy::AsyncAfter) {
            emitAsyncAfterRequestFunction(function, models, writer);
            return;
        }

        if (function.getExecutionPolicy() != ir::IrExecutionPolicy::Sync) {
            failUnsupported("execution policies other than Sync");
        }

        validatePureStatements(function.getStatements());
        emitFunctionSignature(function, writer);
        KotlinExpressionEmitter expressionEmitter(identifierEscaper_);
        KotlinStatementEmitter statementEmitter(
            writer,
            typeMapper_,
            expressionEmitter,
            identifierEscaper_
        );
        statementEmitter.emitStatements(function.getStatements());
        writer.endBlock();
    }

    void KotlinGenerator::emitAsyncAfterRequestFunction(
        const ir::IrFunctionDeclaration& function,
        const ModelMap& models,
        KotlinSourceWriter& writer
    ) const {
        const ir::IrCrossaRequestExpression* request = findReturnedRequest(function);
        if (request == nullptr) {
            failUnsupported("AsyncAfter without returned CrossaRequest");
        }
        if (!function.getParameters().empty()) {
            failUnsupported("AsyncAfter request parameters");
        }

        const string functionName = identifierEscaper_.escape(function.getName());
        const string resultType = typeMapper_.mapValueType(function.getReturnType());
        writer.beginBlock(
            "public fun " + functionName +
            "(callback: (Result<" + resultType + ">) -> Unit)"
        );
        writer.writeLine("Thread {");
        writer.indent();
        writer.writeLine("try {");
        writer.indent();
        writer.writeLine("callback(Result.success(" + functionName + "Blocking()))");
        writer.dedent();
        writer.writeLine("} catch (error: Throwable) {");
        writer.indent();
        writer.writeLine("callback(Result.failure(error))");
        writer.dedent();
        writer.writeLine("}");
        writer.dedent();
        writer.writeLine("}.start()");
        writer.endBlock();
        writer.writeLine();
        emitRequestBlockingFunction(function, *request, models, writer);
    }

    void KotlinGenerator::emitRequestBlockingFunction(
        const ir::IrFunctionDeclaration& function,
        const ir::IrCrossaRequestExpression& request,
        const ModelMap& models,
        KotlinSourceWriter& writer
    ) const {
        if (request.getMethod() != ir::IrHttpMethod::Get) {
            failUnsupported("generated Android request methods other than GET");
        }

        const types::SemanticType& returnType = function.getReturnType();
        if (returnType.getKind() != types::SemanticTypeKind::List ||
            returnType.getElementType() == nullptr ||
            returnType.getElementType()->getKind() !=
                types::SemanticTypeKind::Model) {
            failUnsupported("generated Android request return types other than List<Model>");
        }

        const string modelName = returnType.getElementType()->getModelName();
        if (!models.contains(modelName)) {
            failInvariant("Generated request model is missing.");
        }

        const string functionName = identifierEscaper_.escape(function.getName());
        const string resultType = typeMapper_.mapValueType(returnType);
        const string url = readStringLiteral(request.getUrl());
        const vector<pair<string, string>> headers = readStringMap(request.getHeaders());

        writer.beginBlock("private fun " + functionName + "Blocking(): " + resultType);
        writer.writeLine("val connection = java.net.URL(" + escapeKotlinStringLiteral(url) + ").openConnection() as java.net.HttpURLConnection");
        writer.writeLine("connection.requestMethod = \"GET\"");
        writer.writeLine("connection.connectTimeout = 10000");
        writer.writeLine("connection.readTimeout = 10000");
        writer.writeLine("connection.setRequestProperty(\"Accept\", \"application/json\")");
        for (const pair<string, string>& header : headers) {
            writer.writeLine(
                "connection.setRequestProperty(" +
                escapeKotlinStringLiteral(header.first) + ", " +
                escapeKotlinStringLiteral(header.second) + ")"
            );
        }
        writer.beginBlock("try");
        writer.writeLine("val status = connection.responseCode");
        writer.writeLine("val stream = if (status in 200..299) connection.inputStream else connection.errorStream");
        writer.writeLine("val body = stream.bufferedReader().use { it.readText() }");
        writer.writeLine("if (status !in 200..299) error(\"HTTP $status: $body\")");
        writer.writeLine("val array = org.json.JSONArray(body)");
        writer.beginBlock("return buildList");
        writer.beginBlock("for (index in 0 until array.length())");
        writer.writeLine("add(map" + identifierEscaper_.escape(modelName) + "(array.getJSONObject(index)))");
        writer.endBlock();
        writer.endBlock();
        writer.writeLine("} finally {");
        writer.indent();
        writer.writeLine("connection.disconnect()");
        writer.endBlock();
        writer.endBlock();
    }

    void KotlinGenerator::emitModelMapper(
        const ir::IrModelDeclaration& model,
        KotlinSourceWriter& writer
    ) const {
        const string modelName = identifierEscaper_.escape(model.getName());
        writer.beginBlock(
            "private fun map" + modelName +
            "(json: org.json.JSONObject): " + modelName
        );
        writer.writeLine("return " + modelName + "(");
        writer.indent();
        const vector<ir::IrModelField>& fields = model.getFields();
        for (size_t index = 0; index < fields.size(); ++index) {
            const ir::IrModelField& field = fields[index];
            string reader;
            switch (field.getType().getKind()) {
                case types::SemanticTypeKind::Int:
                    reader = "json.getInt";
                    break;
                case types::SemanticTypeKind::Long:
                    reader = "json.getLong";
                    break;
                case types::SemanticTypeKind::Double:
                    reader = "json.getDouble";
                    break;
                case types::SemanticTypeKind::String:
                    reader = "json.getString";
                    break;
                case types::SemanticTypeKind::Bool:
                    reader = "json.getBoolean";
                    break;
                case types::SemanticTypeKind::Unit:
                case types::SemanticTypeKind::Json:
                case types::SemanticTypeKind::Model:
                case types::SemanticTypeKind::List:
                    failUnsupported("nested generated Android model field type");
            }
            writer.writeLine(
                identifierEscaper_.escape(field.getName()) + " = " +
                reader + "(" + escapeKotlinStringLiteral(field.getName()) + ")" +
                (index + 1 < fields.size() ? "," : "")
            );
        }
        writer.dedent();
        writer.writeLine(")");
        writer.endBlock();
    }

    const ir::IrCrossaRequestExpression*
    KotlinGenerator::findReturnedRequest(
        const ir::IrFunctionDeclaration& function
    ) {
        if (function.getStatements().size() != 1 ||
            function.getStatements().front()->getKind() !=
                ir::IrStatementKind::Return) {
            return nullptr;
        }

        const auto& returnStatement = static_cast<const ir::IrReturnStatement&>(
            *function.getStatements().front()
        );
        if (returnStatement.getExpression().getKind() !=
            ir::IrExpressionKind::CrossaRequest) {
            return nullptr;
        }
        return &static_cast<const ir::IrCrossaRequestExpression&>(
            returnStatement.getExpression()
        );
    }

    string KotlinGenerator::readStringLiteral(
        const ir::IrExpression& expression
    ) {
        if (expression.getKind() != ir::IrExpressionKind::StringBuild) {
            failUnsupported("generated Android non-literal URL");
        }

        const auto& stringBuild = static_cast<const ir::IrStringBuildExpression&>(
            expression
        );
        string value;
        for (const ir::IrStringSegment& segment : stringBuild.getSegments()) {
            if (segment.getKind() != ir::IrStringSegmentKind::Literal) {
                failUnsupported("generated Android interpolated URL");
            }
            value += segment.getValue();
        }
        return value;
    }

    vector<pair<string, string>> KotlinGenerator::readStringMap(
        const ir::IrExpression* expression
    ) {
        if (expression == nullptr) {
            return {};
        }
        if (expression->getKind() != ir::IrExpressionKind::JsonObject) {
            failUnsupported("generated Android non-object headers");
        }

        const auto& object = static_cast<const ir::IrJsonObjectExpression&>(
            *expression
        );
        vector<pair<string, string>> values;
        values.reserve(object.getEntries().size());
        for (const ir::IrJsonObjectEntry& entry : object.getEntries()) {
            values.emplace_back(entry.getKey(), readStringLiteral(entry.getValue()));
        }
        return values;
    }

    string KotlinGenerator::escapeKotlinStringLiteral(const string& value) {
        ostringstream output;
        output << '"';
        for (const unsigned char character : value) {
            switch (character) {
                case '\\':
                    output << "\\\\";
                    break;
                case '"':
                    output << "\\\"";
                    break;
                case '$':
                    output << "\\$";
                    break;
                case '\n':
                    output << "\\n";
                    break;
                case '\r':
                    output << "\\r";
                    break;
                case '\t':
                    output << "\\t";
                    break;
                default:
                    if (character < 0x20) {
                        constexpr char HexDigits[] = "0123456789ABCDEF";
                        output << "\\u00" << HexDigits[character >> 4]
                               << HexDigits[character & 0x0F];
                    } else {
                        output << static_cast<char>(character);
                    }
                    break;
            }
        }
        output << '"';
        return output.str();
    }

    // Emits one Kotlin function signature using the canonical wrapping policy.
    void KotlinGenerator::emitFunctionSignature(
        const ir::IrFunctionDeclaration& function,
        KotlinSourceWriter& writer
    ) const {
        const string functionName = identifierEscaper_.escape(function.getName());
        const bool hasValueResult = !typeMapper_.isUnit(function.getReturnType());
        const string resultType = hasValueResult
            ? ": " + typeMapper_.mapValueType(function.getReturnType())
            : "";
        const vector<ir::IrParameter>& parameters = function.getParameters();
        if (parameters.size() <= 2) {
            string signature = "public fun " + functionName + "(";
            for (size_t index = 0; index < parameters.size(); ++index) {
                if (index > 0) {
                    signature += ", ";
                }
                signature += identifierEscaper_.escape(parameters[index].getName()) +
                    ": " + typeMapper_.mapValueType(parameters[index].getType());
            }
            writer.beginBlock(signature + ")" + resultType);
            return;
        }

        writer.writeLine("public fun " + functionName + "(");
        writer.indent();
        for (size_t index = 0; index < parameters.size(); ++index) {
            writer.writeLine(
                identifierEscaper_.escape(parameters[index].getName()) + ": " +
                typeMapper_.mapValueType(parameters[index].getType()) +
                (index + 1 < parameters.size() ? "," : "")
            );
        }
        writer.dedent();
        writer.beginBlock(
            ")" + resultType
        );
    }

    // Returns the deterministic Kotlin file name for one source unit.
    string KotlinGenerator::getFileName(const ir::Program& program) const {
        return program.getIdentity() + ".kt";
    }

    // Writes the optional validated Kotlin package directive for one source file.
    void KotlinGenerator::emitPackageDirective(
        const optional<string>& packageName,
        KotlinSourceWriter& writer
    ) {
        if (!packageName.has_value()) {
            return;
        }
        if (!isValidPackageName(*packageName)) {
            throw runtime_error(
                "Kotlin config packageName must be a dot-separated sequence "
                "of ASCII identifiers."
            );
        }
        writer.writeLine("package " + *packageName);
        writer.writeLine();
    }

    // Returns whether one configured package name is valid Kotlin package syntax.
    bool KotlinGenerator::isValidPackageName(string_view packageName) noexcept {
        if (packageName.empty()) {
            return false;
        }

        size_t segmentStart = 0;
        while (segmentStart < packageName.size()) {
            const size_t separator = packageName.find('.', segmentStart);
            const size_t segmentLength = separator == string_view::npos
                ? packageName.size() - segmentStart
                : separator - segmentStart;
            if (!isValidPackageSegment(
                    packageName.substr(segmentStart, segmentLength)
                )) {
                return false;
            }
            if (separator == string_view::npos) {
                return true;
            }
            segmentStart = separator + 1;
        }

        return false;
    }

    // Returns whether one package segment is a valid ASCII Kotlin identifier.
    bool KotlinGenerator::isValidPackageSegment(string_view segment) noexcept {
        if (segment.empty()) {
            return false;
        }
        const auto isAsciiLetter = [](const char value) {
            return (value >= 'a' && value <= 'z') ||
                (value >= 'A' && value <= 'Z');
        };
        if (!isAsciiLetter(segment.front()) && segment.front() != '_') {
            return false;
        }
        for (const char value : segment.substr(1)) {
            if (!isAsciiLetter(value) && value != '_' &&
                !(value >= '0' && value <= '9')) {
                return false;
            }
        }
        return true;
    }

    // Rejects runtime-backed expressions before Kotlin source emission begins.
    void KotlinGenerator::validatePureStatements(
        const vector<unique_ptr<ir::IrStatement>>& statements
    ) {
        for (const unique_ptr<ir::IrStatement>& statement : statements) {
            validatePureStatement(*statement);
        }
    }

    // Rejects runtime-backed expressions inside one typed IR statement.
    void KotlinGenerator::validatePureStatement(
        const ir::IrStatement& statement
    ) {
        switch (statement.getKind()) {
            case ir::IrStatementKind::Return:
                validatePureExpression(
                    static_cast<const ir::IrReturnStatement&>(statement)
                        .getExpression()
                );
                return;
            case ir::IrStatementKind::Evaluate:
                validatePureExpression(
                    static_cast<const ir::IrEvaluateStatement&>(statement)
                        .getExpression()
                );
                return;
            case ir::IrStatementKind::Local:
                validatePureExpression(
                    static_cast<const ir::IrLocalStatement&>(statement)
                        .getInitializer()
                );
                return;
            case ir::IrStatementKind::If: {
                const auto& conditional = static_cast<const ir::IrIfStatement&>(
                    statement
                );
                validatePureExpression(conditional.getCondition());
                validatePureStatements(conditional.getThenStatements());
                if (const vector<unique_ptr<ir::IrStatement>>* elseStatements =
                        conditional.getElseStatements();
                    elseStatements != nullptr) {
                    validatePureStatements(*elseStatements);
                }
                return;
            }
        }

        failInvariant("Unknown IR statement kind.");
    }

    // Rejects runtime-backed expressions inside one typed IR expression tree.
    void KotlinGenerator::validatePureExpression(
        const ir::IrExpression& expression
    ) {
        switch (expression.getKind()) {
            case ir::IrExpressionKind::CrossaRequest:
                failUnsupported("runtime-backed expression 'CrossaRequest'");
            case ir::IrExpressionKind::Call: {
                const auto& call = static_cast<const ir::IrCallExpression&>(
                    expression
                );
                for (const unique_ptr<ir::IrExpression>& argument :
                     call.getArguments()) {
                    validatePureExpression(*argument);
                }
                return;
            }
            case ir::IrExpressionKind::Unary:
                validatePureExpression(
                    static_cast<const ir::IrUnaryExpression&>(expression)
                        .getOperand()
                );
                return;
            case ir::IrExpressionKind::Binary: {
                const auto& binary = static_cast<const ir::IrBinaryExpression&>(
                    expression
                );
                validatePureExpression(binary.getLeft());
                validatePureExpression(binary.getRight());
                return;
            }
            case ir::IrExpressionKind::JsonObject: {
                const auto& object = static_cast<const ir::IrJsonObjectExpression&>(
                    expression
                );
                for (const ir::IrJsonObjectEntry& entry : object.getEntries()) {
                    validatePureExpression(entry.getValue());
                }
                return;
            }
            case ir::IrExpressionKind::JsonArray: {
                const auto& array = static_cast<const ir::IrJsonArrayExpression&>(
                    expression
                );
                for (const unique_ptr<ir::IrExpression>& value :
                     array.getValues()) {
                    validatePureExpression(*value);
                }
                return;
            }
            case ir::IrExpressionKind::ReadSymbol:
            case ir::IrExpressionKind::IntegerConstant:
            case ir::IrExpressionKind::DoubleConstant:
            case ir::IrExpressionKind::StringBuild:
            case ir::IrExpressionKind::BooleanConstant:
            case ir::IrExpressionKind::JsonNumber:
            case ir::IrExpressionKind::JsonNull:
                return;
        }

        failInvariant("Unknown IR expression kind.");
    }

    // Raises a deterministic unsupported-backend diagnostic for one IR feature.
    [[noreturn]] void KotlinGenerator::failUnsupported(const char* feature) {
        throw runtime_error(
            string("Kotlin generation does not support ") + feature + "."
        );
    }

    // Raises a deterministic internal invariant diagnostic for malformed IR.
    [[noreturn]] void KotlinGenerator::failInvariant(const char* message) {
        throw runtime_error(
            string("Kotlin generation invariant failed: ") + message
        );
    }

}
