#include "crossa/compiler/generators/kotlin/KotlinGenerator.h"

#include <cstdint>
#include <limits>
#include <stdexcept>

#include "crossa/compiler/generators/kotlin/KotlinExpressionEmitter.h"
#include "crossa/compiler/generators/kotlin/KotlinSourceWriter.h"
#include "crossa/compiler/generators/kotlin/KotlinStatementEmitter.h"
#include "crossa/compiler/ir/IrJsonExpression.h"

using namespace std;

namespace crossa::compiler::generators::kotlin {

    // Generates one deterministic Kotlin source unit from validated IR.
    KotlinGeneratedSource KotlinGenerator::generate(
        const ir::Program& program,
        const optional<string>& packageName,
        KotlinGenerationTarget target
    ) const {
        if (program.getIdentity().empty()) {
            failInvariant("Program source-unit identity is empty.");
        }
        KotlinSourceWriter writer;
        writer.writeLine("// Generated by Crossa. Do not edit.");
        writer.writeLine();
        emitPackageDirective(packageName, writer);
        writer.beginBlock("public class " + identifierEscaper_.escape(program.getIdentity()));
        ModelMap models;
        for (const unique_ptr<ir::IrDeclaration>& declaration : program.getDeclarations()) {
            if (declaration->getKind() == ir::IrDeclarationKind::Model) {
                const auto& model = static_cast<const ir::IrModelDeclaration&>(*declaration);
                models.emplace(model.getName(), &model);
            }
        }
        for (const unique_ptr<ir::IrDeclaration>& declaration : program.getDeclarations()) {
            if (declaration->getKind() == ir::IrDeclarationKind::Model) {
                if (target == KotlinGenerationTarget::Pure) {
                    failUnsupported("top-level declaration");
                }
                writer.writeLine();
                const auto& model = static_cast<const ir::IrModelDeclaration&>(*declaration);
                emitNativeModel(model, writer);
            } else if (declaration->getKind() == ir::IrDeclarationKind::Function) {
                writer.writeLine();
                emitFunction(
                    static_cast<const ir::IrFunctionDeclaration&>(*declaration),
                    models,
                    target,
                    program.getIdentity(),
                    writer
                );
            } else if (declaration->getKind() != ir::IrDeclarationKind::Expression) {
                failUnsupported("top-level declaration");
            }
        }
        writer.endBlock();
        return KotlinGeneratedSource(getFileName(program), writer.getSource());
    }

    // Emits a Kotlin data class for a model used by the pure backend.
    void KotlinGenerator::emitModel(const ir::IrModelDeclaration& model, KotlinSourceWriter& writer) const {
        writer.writeLine("public data class " + identifierEscaper_.escape(model.getName()) + "(");
        writer.indent();
        const vector<ir::IrModelField>& fields = model.getFields();
        for (size_t index = 0; index < fields.size(); ++index) {
            writer.writeLine("public val " + identifierEscaper_.escape(fields[index].getName()) + ": " + typeMapper_.mapValueType(fields[index].getType()) + (index + 1 < fields.size() ? "," : ""));
        }
        writer.dedent();
        writer.writeLine(")");
    }

    // Emits either one pure function or a native Android operation wrapper.
    void KotlinGenerator::emitFunction(
        const ir::IrFunctionDeclaration& function,
        const ModelMap& models,
        KotlinGenerationTarget target,
        const string& sourceIdentity,
        KotlinSourceWriter& writer
    ) const {
        (void)models;
        if (target == KotlinGenerationTarget::AndroidNative && function.getExecutionPolicy() != ir::IrExecutionPolicy::Sync) {
            emitNativeFunction(function, sourceIdentity, writer);
            return;
        }
        if (function.getExecutionPolicy() != ir::IrExecutionPolicy::Sync) {
            failUnsupported("execution policies other than Sync");
        }
        if (target == KotlinGenerationTarget::Pure) {
            for (const ir::IrParameter& parameter : function.getParameters()) {
                if (parameter.getType().getKind() ==
                    types::SemanticTypeKind::List) {
                    throw runtime_error(
                        "Kotlin generation does not support type '" +
                        parameter.getType().format() + "'."
                    );
                }
            }
            if (function.getReturnType().getKind() ==
                types::SemanticTypeKind::List) {
                throw runtime_error(
                    "Kotlin generation does not support type '" +
                    function.getReturnType().format() + "'."
                );
            }
        }
        validatePureStatements(function.getStatements());
        emitFunctionSignature(function, writer);
        KotlinExpressionEmitter expressionEmitter(identifierEscaper_);
        KotlinStatementEmitter statementEmitter(writer, typeMapper_, expressionEmitter, identifierEscaper_);
        statementEmitter.emitStatements(function.getStatements());
        writer.endBlock();
    }

    // Emits a native-backed Android entry point without generated network work.
    void KotlinGenerator::emitNativeFunction(
        const ir::IrFunctionDeclaration& function,
        const string& sourceIdentity,
        KotlinSourceWriter& writer
    ) const {
        string signature = "public fun " + identifierEscaper_.escape(function.getName()) + "(";
        const vector<ir::IrParameter>& parameters = function.getParameters();
        for (size_t index = 0; index < parameters.size(); ++index) {
            if (index > 0) signature += ", ";
            signature += identifierEscaper_.escape(parameters[index].getName()) + ": " + typeMapper_.mapValueType(parameters[index].getType());
        }
        if (function.getExecutionPolicy() == ir::IrExecutionPolicy::AsyncAfter) {
            if (!parameters.empty()) signature += ", ";
            signature += "onState: (CrossaState<" + typeMapper_.mapValueType(function.getReturnType()) + ">) -> Unit";
        }
        writer.beginBlock(signature + ")");
        string arguments = "arrayOf(";
        for (size_t index = 0; index < parameters.size(); ++index) {
            if (index > 0) arguments += ", ";
            arguments += "CrossaArgument.from(" + identifierEscaper_.escape(parameters[index].getName()) + ")";
        }
        arguments += ")";
        const string identifier = operationLiteral(sourceIdentity, function);
        if (function.getExecutionPolicy() == ir::IrExecutionPolicy::Async) {
            writer.writeLine("CrossaNativeBridge.invokeAsync(CrossaRuntime.requireHandle(), " + identifier + ", " + arguments + ")");
        } else {
            const types::SemanticType& resultType = function.getReturnType();
            string mapper;
            if (resultType.getKind() == types::SemanticTypeKind::List &&
                resultType.getElementType() != nullptr &&
                resultType.getElementType()->getKind() ==
                    types::SemanticTypeKind::Model) {
                const string model = identifierEscaper_.escape(
                    resultType.getElementType()->getModelName()
                );
                mapper = "{ result -> CrossaNativeList(result) { handle -> " +
                    model + "(result, handle) } }";
            } else if (resultType.getKind() == types::SemanticTypeKind::Model) {
                mapper = "{ result -> " + identifierEscaper_.escape(
                    resultType.getModelName()
                ) + "(result, result.rootModelHandle()) }";
            } else {
                switch (resultType.getKind()) {
                    case types::SemanticTypeKind::Int:
                        mapper = "{ result -> result.intValue() }";
                        break;
                    case types::SemanticTypeKind::Long:
                        mapper = "{ result -> result.longValue() }";
                        break;
                    case types::SemanticTypeKind::Double:
                        mapper = "{ result -> result.doubleValue() }";
                        break;
                    case types::SemanticTypeKind::String:
                        mapper = "{ result -> result.stringValue() }";
                        break;
                    case types::SemanticTypeKind::Bool:
                        mapper = "{ result -> result.booleanValue() }";
                        break;
                    case types::SemanticTypeKind::Unit:
                    case types::SemanticTypeKind::Json:
                    case types::SemanticTypeKind::Model:
                    case types::SemanticTypeKind::List:
                        failUnsupported("native-backed Android result type");
                }
            }
            writer.writeLine("CrossaNativeBridge.invokeAsyncAfter(CrossaRuntime.requireHandle(), " + identifier + ", " + arguments + ", " + mapper + ", onState)");
        }
        writer.endBlock();
    }

    // Emits a lazy native-backed Android model view using declaration-order fields.
    void KotlinGenerator::emitNativeModel(const ir::IrModelDeclaration& model, KotlinSourceWriter& writer) const {
        writer.beginBlock("public class " + identifierEscaper_.escape(model.getName()) + " internal constructor(private val owner: CrossaNativeResult, private val handle: Long)");
        const vector<ir::IrModelField>& fields = model.getFields();
        for (size_t index = 0; index < fields.size(); ++index) {
            const ir::IrModelField& field = fields[index];
            writer.writeLine();
            writer.writeLine("public val " + identifierEscaper_.escape(field.getName()) + ": " + typeMapper_.mapValueType(field.getType()));
            writer.indent();
            const string fieldId = to_string(index);
            switch (field.getType().getKind()) {
                case types::SemanticTypeKind::Int: writer.writeLine("get() = CrossaNativeBridge.modelInt(owner, handle, " + fieldId + ")"); break;
                case types::SemanticTypeKind::Long: writer.writeLine("get() = CrossaNativeBridge.modelLong(owner, handle, " + fieldId + ")"); break;
                case types::SemanticTypeKind::Double: writer.writeLine("get() = CrossaNativeBridge.modelDouble(owner, handle, " + fieldId + ")"); break;
                case types::SemanticTypeKind::String: writer.writeLine("get() = CrossaNativeBridge.modelString(owner, handle, " + fieldId + ")"); break;
                case types::SemanticTypeKind::Bool: writer.writeLine("get() = CrossaNativeBridge.modelBoolean(owner, handle, " + fieldId + ")"); break;
                case types::SemanticTypeKind::Unit:
                case types::SemanticTypeKind::Json:
                case types::SemanticTypeKind::Model:
                case types::SemanticTypeKind::List:
                    failUnsupported("native-backed Android model field type");
            }
            writer.dedent();
        }
        writer.endBlock();
    }

    // Derives one stable FNV-1a operation identifier from a Crossa signature.
    uint64_t KotlinGenerator::operationId(
        const string& sourceIdentity,
        const ir::IrFunctionDeclaration& function
    ) noexcept {
        uint64_t value = 1469598103934665603ULL;
        const string signature = sourceIdentity + ":" + function.getName() + ":" + function.getReturnType().format();
        for (const char character : signature) {
            value ^= static_cast<unsigned char>(character);
            value *= 1099511628211ULL;
        }
        return value;
    }

    // Formats one operation identifier as a Kotlin Long literal.
    string KotlinGenerator::operationLiteral(
        const string& sourceIdentity,
        const ir::IrFunctionDeclaration& function
    ) {
        const uint64_t value = operationId(sourceIdentity, function);
        const int64_t signedValue = static_cast<int64_t>(value);
        return to_string(signedValue) + "L";
    }

    // Emits one pure Kotlin function signature.
    void KotlinGenerator::emitFunctionSignature(const ir::IrFunctionDeclaration& function, KotlinSourceWriter& writer) const {
        const vector<ir::IrParameter>& parameters = function.getParameters();
        const string result = typeMapper_.isUnit(function.getReturnType()) ? "" : ": " + typeMapper_.mapValueType(function.getReturnType());
        if (parameters.size() > 2) {
            writer.writeLine("public fun " + identifierEscaper_.escape(function.getName()) + "(");
            writer.indent();
            for (size_t index = 0; index < parameters.size(); ++index) {
                writer.writeLine(identifierEscaper_.escape(parameters[index].getName()) + ": " + typeMapper_.mapValueType(parameters[index].getType()) + (index + 1 < parameters.size() ? "," : ""));
            }
            writer.dedent();
            writer.beginBlock(")" + result);
            return;
        }
        string signature = "public fun " + identifierEscaper_.escape(function.getName()) + "(";
        for (size_t index = 0; index < parameters.size(); ++index) {
            if (index > 0) signature += ", ";
            signature += identifierEscaper_.escape(parameters[index].getName()) + ": " + typeMapper_.mapValueType(parameters[index].getType());
        }
        writer.beginBlock(signature + ")" + result);
    }

    // Returns the deterministic Kotlin file name for a source unit.
    string KotlinGenerator::getFileName(const ir::Program& program) const { return program.getIdentity() + ".kt"; }

    // Writes a validated Kotlin package directive when configured.
    void KotlinGenerator::emitPackageDirective(const optional<string>& packageName, KotlinSourceWriter& writer) {
        if (!packageName.has_value()) return;
        if (!isValidPackageName(*packageName)) throw runtime_error("Kotlin config packageName is invalid.");
        writer.writeLine("package " + *packageName);
        writer.writeLine();
    }

    // Returns whether a dot-separated package is valid Kotlin package syntax.
    bool KotlinGenerator::isValidPackageName(string_view packageName) noexcept {
        if (packageName.empty()) return false;
        size_t start = 0;
        while (start < packageName.size()) {
            const size_t separator = packageName.find('.', start);
            const size_t length = separator == string_view::npos ? packageName.size() - start : separator - start;
            if (!isValidPackageSegment(packageName.substr(start, length))) return false;
            if (separator == string_view::npos) return true;
            start = separator + 1;
        }
        return false;
    }

    // Returns whether a package segment is a valid ASCII Kotlin identifier.
    bool KotlinGenerator::isValidPackageSegment(string_view segment) noexcept {
        if (segment.empty()) return false;
        const auto isLetter = [](char value) { return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z'); };
        if (!isLetter(segment.front()) && segment.front() != '_') return false;
        for (const char value : segment.substr(1)) if (!isLetter(value) && value != '_' && !(value >= '0' && value <= '9')) return false;
        return true;
    }

    // Validates that pure source generation contains no runtime-backed work.
    void KotlinGenerator::validatePureStatements(const vector<unique_ptr<ir::IrStatement>>& statements) {
        for (const unique_ptr<ir::IrStatement>& statement : statements) validatePureStatement(*statement);
    }

    // Validates one IR statement for pure Kotlin generation.
    void KotlinGenerator::validatePureStatement(const ir::IrStatement& statement) {
        switch (statement.getKind()) {
            case ir::IrStatementKind::Return: validatePureExpression(static_cast<const ir::IrReturnStatement&>(statement).getExpression()); return;
            case ir::IrStatementKind::Evaluate: validatePureExpression(static_cast<const ir::IrEvaluateStatement&>(statement).getExpression()); return;
            case ir::IrStatementKind::Local: validatePureExpression(static_cast<const ir::IrLocalStatement&>(statement).getInitializer()); return;
            case ir::IrStatementKind::If: {
                const auto& conditional = static_cast<const ir::IrIfStatement&>(statement);
                validatePureExpression(conditional.getCondition());
                validatePureStatements(conditional.getThenStatements());
                if (const auto* alternative = conditional.getElseStatements(); alternative != nullptr) validatePureStatements(*alternative);
                return;
            }
        }
        failInvariant("Unknown IR statement kind.");
    }

    // Validates one IR expression tree for pure Kotlin generation.
    void KotlinGenerator::validatePureExpression(const ir::IrExpression& expression) {
        switch (expression.getKind()) {
            case ir::IrExpressionKind::CrossaRequest: failUnsupported("runtime-backed expression 'CrossaRequest'");
            case ir::IrExpressionKind::Call: {
                const auto& call = static_cast<const ir::IrCallExpression&>(expression);
                for (const unique_ptr<ir::IrExpression>& argument : call.getArguments()) validatePureExpression(*argument);
                return;
            }
            case ir::IrExpressionKind::Unary: validatePureExpression(static_cast<const ir::IrUnaryExpression&>(expression).getOperand()); return;
            case ir::IrExpressionKind::Binary: {
                const auto& binary = static_cast<const ir::IrBinaryExpression&>(expression);
                validatePureExpression(binary.getLeft()); validatePureExpression(binary.getRight()); return;
            }
            case ir::IrExpressionKind::JsonObject: {
                const auto& object = static_cast<const ir::IrJsonObjectExpression&>(expression);
                for (const ir::IrJsonObjectEntry& entry : object.getEntries()) validatePureExpression(entry.getValue());
                return;
            }
            case ir::IrExpressionKind::JsonArray: {
                const auto& array = static_cast<const ir::IrJsonArrayExpression&>(expression);
                for (const unique_ptr<ir::IrExpression>& value : array.getValues()) validatePureExpression(*value);
                return;
            }
            case ir::IrExpressionKind::ReadSymbol:
            case ir::IrExpressionKind::IntegerConstant:
            case ir::IrExpressionKind::DoubleConstant:
            case ir::IrExpressionKind::StringBuild:
            case ir::IrExpressionKind::BooleanConstant:
            case ir::IrExpressionKind::JsonNumber:
            case ir::IrExpressionKind::JsonNull:
                return;
        }
        failInvariant("Unknown IR expression kind.");
    }

    // Raises a deterministic unsupported-generation diagnostic.
    [[noreturn]] void KotlinGenerator::failUnsupported(const char* feature) { throw runtime_error(string("Kotlin generation does not support ") + feature + "."); }

    // Raises a deterministic malformed-IR diagnostic.
    [[noreturn]] void KotlinGenerator::failInvariant(const char* message) { throw runtime_error(string("Kotlin generation invariant failed: ") + message); }

}
