#include "crossa/compiler/generators/kotlin/KotlinGenerator.h"

#include <stdexcept>

#include "crossa/compiler/generators/kotlin/KotlinExpressionEmitter.h"
#include "crossa/compiler/generators/kotlin/KotlinSourceWriter.h"
#include "crossa/compiler/generators/kotlin/KotlinStatementEmitter.h"
#include "crossa/compiler/ir/IrJsonExpression.h"

using namespace std;

namespace crossa::compiler::generators::kotlin {

    // Generates the Kotlin file identity and canonical source for one IR program.
    KotlinGeneratedSource KotlinGenerator::generate(
        const ir::Program& program,
        const optional<string>& packageName
    ) const {
        if (program.getIdentity().empty()) {
            failInvariant("Program source-unit identity is empty.");
        }

        KotlinSourceWriter writer;
        writer.writeLine("// Generated by Crossa. Do not edit.");
        writer.writeLine();
        emitPackageDirective(packageName, writer);
        writer.beginBlock(
            "public class " + identifierEscaper_.escape(program.getIdentity())
        );

        for (const unique_ptr<ir::IrDeclaration>& declaration :
             program.getDeclarations()) {
            if (declaration->getKind() != ir::IrDeclarationKind::Function) {
                failUnsupported("top-level declaration");
            }
            writer.writeLine();
            emitFunction(
                static_cast<const ir::IrFunctionDeclaration&>(*declaration),
                writer
            );
        }

        writer.endBlock();
        return KotlinGeneratedSource(getFileName(program), writer.getSource());
    }

    // Emits one pure synchronous Kotlin function.
    void KotlinGenerator::emitFunction(
        const ir::IrFunctionDeclaration& function,
        KotlinSourceWriter& writer
    ) const {
        if (function.getExecutionPolicy() != ir::IrExecutionPolicy::Sync) {
            failUnsupported("execution policies other than Sync");
        }

        validatePureStatements(function.getStatements());
        emitFunctionSignature(function, writer);
        KotlinExpressionEmitter expressionEmitter(identifierEscaper_);
        KotlinStatementEmitter statementEmitter(
            writer,
            typeMapper_,
            expressionEmitter,
            identifierEscaper_
        );
        statementEmitter.emitStatements(function.getStatements());
        writer.endBlock();
    }

    // Emits one Kotlin function signature using the canonical wrapping policy.
    void KotlinGenerator::emitFunctionSignature(
        const ir::IrFunctionDeclaration& function,
        KotlinSourceWriter& writer
    ) const {
        const string functionName = identifierEscaper_.escape(function.getName());
        const bool hasValueResult = !typeMapper_.isUnit(function.getReturnType());
        const string resultType = hasValueResult
            ? ": " + typeMapper_.mapValueType(function.getReturnType())
            : "";
        const vector<ir::IrParameter>& parameters = function.getParameters();
        if (parameters.size() <= 2) {
            string signature = "public fun " + functionName + "(";
            for (size_t index = 0; index < parameters.size(); ++index) {
                if (index > 0) {
                    signature += ", ";
                }
                signature += identifierEscaper_.escape(parameters[index].getName()) +
                    ": " + typeMapper_.mapValueType(parameters[index].getType());
            }
            writer.beginBlock(signature + ")" + resultType);
            return;
        }

        writer.writeLine("public fun " + functionName + "(");
        writer.indent();
        for (size_t index = 0; index < parameters.size(); ++index) {
            writer.writeLine(
                identifierEscaper_.escape(parameters[index].getName()) + ": " +
                typeMapper_.mapValueType(parameters[index].getType()) +
                (index + 1 < parameters.size() ? "," : "")
            );
        }
        writer.dedent();
        writer.beginBlock(
            ")" + resultType
        );
    }

    // Returns the deterministic Kotlin file name for one source unit.
    string KotlinGenerator::getFileName(const ir::Program& program) const {
        return program.getIdentity() + ".kt";
    }

    // Writes the optional validated Kotlin package directive for one source file.
    void KotlinGenerator::emitPackageDirective(
        const optional<string>& packageName,
        KotlinSourceWriter& writer
    ) {
        if (!packageName.has_value()) {
            return;
        }
        if (!isValidPackageName(*packageName)) {
            throw runtime_error(
                "Kotlin config packageName must be a dot-separated sequence "
                "of ASCII identifiers."
            );
        }
        writer.writeLine("package " + *packageName);
        writer.writeLine();
    }

    // Returns whether one configured package name is valid Kotlin package syntax.
    bool KotlinGenerator::isValidPackageName(string_view packageName) noexcept {
        if (packageName.empty()) {
            return false;
        }

        size_t segmentStart = 0;
        while (segmentStart < packageName.size()) {
            const size_t separator = packageName.find('.', segmentStart);
            const size_t segmentLength = separator == string_view::npos
                ? packageName.size() - segmentStart
                : separator - segmentStart;
            if (!isValidPackageSegment(
                    packageName.substr(segmentStart, segmentLength)
                )) {
                return false;
            }
            if (separator == string_view::npos) {
                return true;
            }
            segmentStart = separator + 1;
        }

        return false;
    }

    // Returns whether one package segment is a valid ASCII Kotlin identifier.
    bool KotlinGenerator::isValidPackageSegment(string_view segment) noexcept {
        if (segment.empty()) {
            return false;
        }
        const auto isAsciiLetter = [](const char value) {
            return (value >= 'a' && value <= 'z') ||
                (value >= 'A' && value <= 'Z');
        };
        if (!isAsciiLetter(segment.front()) && segment.front() != '_') {
            return false;
        }
        for (const char value : segment.substr(1)) {
            if (!isAsciiLetter(value) && value != '_' &&
                !(value >= '0' && value <= '9')) {
                return false;
            }
        }
        return true;
    }

    // Rejects runtime-backed expressions before Kotlin source emission begins.
    void KotlinGenerator::validatePureStatements(
        const vector<unique_ptr<ir::IrStatement>>& statements
    ) {
        for (const unique_ptr<ir::IrStatement>& statement : statements) {
            validatePureStatement(*statement);
        }
    }

    // Rejects runtime-backed expressions inside one typed IR statement.
    void KotlinGenerator::validatePureStatement(
        const ir::IrStatement& statement
    ) {
        switch (statement.getKind()) {
            case ir::IrStatementKind::Return:
                validatePureExpression(
                    static_cast<const ir::IrReturnStatement&>(statement)
                        .getExpression()
                );
                return;
            case ir::IrStatementKind::Evaluate:
                validatePureExpression(
                    static_cast<const ir::IrEvaluateStatement&>(statement)
                        .getExpression()
                );
                return;
            case ir::IrStatementKind::Local:
                validatePureExpression(
                    static_cast<const ir::IrLocalStatement&>(statement)
                        .getInitializer()
                );
                return;
            case ir::IrStatementKind::If: {
                const auto& conditional = static_cast<const ir::IrIfStatement&>(
                    statement
                );
                validatePureExpression(conditional.getCondition());
                validatePureStatements(conditional.getThenStatements());
                if (const vector<unique_ptr<ir::IrStatement>>* elseStatements =
                        conditional.getElseStatements();
                    elseStatements != nullptr) {
                    validatePureStatements(*elseStatements);
                }
                return;
            }
        }

        failInvariant("Unknown IR statement kind.");
    }

    // Rejects runtime-backed expressions inside one typed IR expression tree.
    void KotlinGenerator::validatePureExpression(
        const ir::IrExpression& expression
    ) {
        switch (expression.getKind()) {
            case ir::IrExpressionKind::CrossaRequest:
                failUnsupported("runtime-backed expression 'CrossaRequest'");
            case ir::IrExpressionKind::Call: {
                const auto& call = static_cast<const ir::IrCallExpression&>(
                    expression
                );
                for (const unique_ptr<ir::IrExpression>& argument :
                     call.getArguments()) {
                    validatePureExpression(*argument);
                }
                return;
            }
            case ir::IrExpressionKind::Unary:
                validatePureExpression(
                    static_cast<const ir::IrUnaryExpression&>(expression)
                        .getOperand()
                );
                return;
            case ir::IrExpressionKind::Binary: {
                const auto& binary = static_cast<const ir::IrBinaryExpression&>(
                    expression
                );
                validatePureExpression(binary.getLeft());
                validatePureExpression(binary.getRight());
                return;
            }
            case ir::IrExpressionKind::JsonObject: {
                const auto& object = static_cast<const ir::IrJsonObjectExpression&>(
                    expression
                );
                for (const ir::IrJsonObjectEntry& entry : object.getEntries()) {
                    validatePureExpression(entry.getValue());
                }
                return;
            }
            case ir::IrExpressionKind::JsonArray: {
                const auto& array = static_cast<const ir::IrJsonArrayExpression&>(
                    expression
                );
                for (const unique_ptr<ir::IrExpression>& value :
                     array.getValues()) {
                    validatePureExpression(*value);
                }
                return;
            }
            case ir::IrExpressionKind::ReadSymbol:
            case ir::IrExpressionKind::IntegerConstant:
            case ir::IrExpressionKind::DoubleConstant:
            case ir::IrExpressionKind::StringBuild:
            case ir::IrExpressionKind::BooleanConstant:
            case ir::IrExpressionKind::JsonNumber:
            case ir::IrExpressionKind::JsonNull:
                return;
        }

        failInvariant("Unknown IR expression kind.");
    }

    // Raises a deterministic unsupported-backend diagnostic for one IR feature.
    [[noreturn]] void KotlinGenerator::failUnsupported(const char* feature) {
        throw runtime_error(
            string("Kotlin generation does not support ") + feature + "."
        );
    }

    // Raises a deterministic internal invariant diagnostic for malformed IR.
    [[noreturn]] void KotlinGenerator::failInvariant(const char* message) {
        throw runtime_error(
            string("Kotlin generation invariant failed: ") + message
        );
    }

}
