name: Crossa CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes cmake ninja-build libcurl4-openssl-dev socat

      - name: Build and run all tests
        run: ./test.sh
